(test
 (name test_hpke)
 (modules test_hpke)
 (libraries hpke alcotest qcheck-alcotest mirage-crypto-rng))

(test
 (name test_vectors)
 (modules test_vectors)
 (libraries hpke alcotest mirage-crypto-rng yojson)
 (deps ../test-vectors/rfc9180-supported.json)
 (action
  (setenv
   HPKE_TEST_VECTORS
   %{dep:../test-vectors/rfc9180-supported.json}
   (run %{test}))))
