(test
 (name test_hpke)
 (modules test_hpke)
 (libraries hpke hpke.for_testing alcotest qcheck-alcotest mirage-crypto-rng))

(test
 (name test_vectors)
 (modules test_vectors)
 (libraries hpke hpke.for_testing alcotest mirage-crypto-rng yojson)
 (deps
  ../test-vectors/rfc9180-supported.json
  ../test-vectors/hpke-pq-supported.json)
 (action
  (setenv
   HPKE_TEST_VECTORS
   %{dep:../test-vectors/rfc9180-supported.json}
   (setenv
    HPKE_PQ_TEST_VECTORS
    %{dep:../test-vectors/hpke-pq-supported.json}
    (run %{test})))))
